{{ range $i, $a1sim := .Values.a1Sims }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $a1sim.name }}"
  labels:
    sim-name: {{ $a1sim.name }}
    release: {{ $.Release.Name }}
    chart: {{ $.Chart.Name }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - name: http
      port: {{ $.Values.service.ports.httpPort }}
    - name: https
      port: {{ $.Values.service.ports.httpsPort }}
  selector:
    sim-name: {{ $a1sim.name }}
    release: {{ $.Release.Name }}
    chart: {{ $.Chart.Name }}

{{ end }}
