#=======================================================================
# Copyright (c) 2017-2020 Aarna Networks, Inc.
# All rights reserved.
# ======================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#           http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================  

global:
  nodePortPrefixExt: 304
  persistence: {}
#################################################################
# Application configuration defaults.
#################################################################
# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}

namespace: onap4k8s
# probe configuration parameters
liveness:
  initialDelaySeconds: 10
  periodSeconds: 30
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: true

readiness:
  initialDelaySeconds: 10
  periodSeconds: 30

middleend:
  service:
    type: NodePort
    name: middleend 
    portName: middleend 
    internalPort: 9081
    externalPort: 9081
    nodePort: 81
    label: middleend

  image:
    registry: registry.hub.docker.com
    repository: amcop/middleend
    tag: master
    pullPolicy: Always

emcoui:
  service:
    type: NodePort
    name: emcoui
    portName: emcoui
    internalPort: 9080
    externalPort: 9080
    nodePort: 80
    label: emcoui

  image:
    registry: registry.hub.docker.com
    repository: amcop/emcoui
    tag: master
    pullPolicy: Always

authproxy:
  # These values should be updated at the time of deployment
  issuer: http://192.168.122.224:31064/auth/realms/EMCO/
  redirect_uri: http://192.168.122.224:30481/middleend/callback
  client_id: emcoapp

ingress:
  enabled: false

# Configure resource requests and limits
flavor: large
resources:
  small:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 5m
      memory: 5Mi
  large:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 5m
      memory: 50Mi
  unlimited: {}
