---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- import_playbook: preconfigure-sriov.yml
- hosts: localhost
  vars:
    sriov_enabled: "{{ groups['kube-node'] | map('extract', hostvars, ['SRIOV_ENABLED']) | select() | list | length > 0 }}"
  tasks:
    - name: Apply Multus
      shell: "/usr/local/bin/kubectl apply -f {{ playbook_dir }}/../images/multus-daemonset.yml"
      when: sriov_enabled
    - name: Apply SRIOV CNI
      shell: "/usr/local/bin/kubectl apply -f {{ playbook_dir }}/../images/sriov-cni.yml"
      when: sriov_enabled
    - name: Apply SRIOV DaemonSet
      shell: "/usr/local/bin/kubectl apply -f {{ playbook_dir }}/../images/sriov-daemonset.yml"
      when: sriov_enabled
    - name: Apply SRIOV Network Attachment definition
      shell: "/usr/local/bin/kubectl apply -f {{ playbook_dir }}/sriov-nad.yml"
      when: sriov_enabled
